import java.awt.Color;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.HashMap;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import javax.swing.border.EmptyBorder;

import org.jfree.ui.ApplicationFrame;

public class Graficas extends JFrame {

	/**
	 * Autogenerated
	 */
	private static final long serialVersionUID = 6009085444561720846L;
	
	Color colorprincipal = Color.WHITE;
	
	private static JPanel contentPane;
	private static ApplicationFrame graphsapp;
	
	
	public static void main(String[] args) throws IOException {
		Graficas grafica = new Graficas();
		HashMap<Integer, Double> tEjecucion = new HashMap<>();
		HashMap<Integer, Double> tSincro = new HashMap<>();
		HashMap<Integer, Double> tTotal = new HashMap<>();
		HashMap<Integer, Double> pUtil = new HashMap<>();
		
		Valores valores1 = LogParser.parseOut("out/out1.txt");
		Valores valores2 = LogParser.parseOut("out/out2.txt");
		Valores valores3 = LogParser.parseOut("out/out3.txt");
		Valores valores4 = LogParser.parseOut("out/out4.txt");
		Valores valores5 = LogParser.parseOut("out/out5.txt");
		
		tEjecucion.put(1, valores1.gettEjecucion());
		tEjecucion.put(2, valores2.gettEjecucion());
		tEjecucion.put(3, valores3.gettEjecucion());
		tEjecucion.put(4, valores4.gettEjecucion());
		tEjecucion.put(5, valores5.gettEjecucion());

		tSincro.put(1, valores1.gettSincro());
		tSincro.put(2, valores2.gettSincro());
		tSincro.put(3, valores3.gettSincro());
		tSincro.put(4, valores4.gettSincro());
		tSincro.put(5, valores5.gettSincro());

		tTotal.put(1, valores1.gettTotal());
		tTotal.put(2, valores2.gettTotal());
		tTotal.put(3, valores3.gettTotal());
		tTotal.put(4, valores4.gettTotal());
		tTotal.put(5, valores5.gettTotal());

		pUtil.put(1, valores1.getpUtil());
		pUtil.put(2, valores2.getpUtil());
		pUtil.put(3, valores3.getpUtil());
		pUtil.put(4, valores4.getpUtil());
		pUtil.put(5, valores5.getpUtil());
		
		graphsapp = new OverlaidPlot("Tiempo de ejecución", contentPane,tEjecucion);
		graphsapp.pack();
		graphsapp = new OverlaidPlot("Tiempo de sincronización", contentPane,tSincro);
		graphsapp.pack();
		graphsapp = new OverlaidPlot("Tiempo total", contentPane, tTotal);
		graphsapp.pack();
		graphsapp = new OverlaidPlot("Porcentaje de utilidad de CPU", contentPane, pUtil);
		graphsapp.pack();
		
		grafica.setVisible(true);
	}
	
	public Graficas() {
		super();
		setTitle("Gráficas");
		setBounds(250, 150, 1200, 800);
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		/** Content Pane */
		contentPane = new JPanel();
		contentPane.setBackground(colorprincipal);
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		contentPane.setLayout(new GridLayout(2, 2));
		setContentPane(contentPane);
	}

}
