package Graficas;
import java.awt.Color;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.HashMap;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import javax.swing.border.EmptyBorder;

import org.jfree.ui.ApplicationFrame;

public class Graficas extends JFrame {

	/**
	 * Autogenerated
	 */
	private static final long serialVersionUID = 6009085444561720846L;
	
	Color colorprincipal = Color.WHITE;
	
	private static JPanel contentPane;
	private static ApplicationFrame graphsapp;
	
	/**
	 * 
	 * @param args inDir
	 * @throws IOException
	 */
	public static void main(String[] args) throws IOException {

		if(args.length != 1) {
			System.out.println("Uso de programa: java Graficas dirOuts");
			return;
		}

		String inDir = args[0] + "/";
		
		Graficas grafica = new Graficas();
		HashMap<Integer, Double> tEjecucion = new HashMap<>();
		HashMap<Integer, Double> tSincro = new HashMap<>();
		HashMap<Integer, Double> tTotal = new HashMap<>();
		HashMap<Integer, Double> pUtil = new HashMap<>();
		
		int num_outs = LogParser.cuentaOuts(inDir);
		
		for (int i = 1; i <= num_outs; i++) {
			String fichero = inDir + "out" + i + ".txt";
			Valores valores = LogParser.parseOut(fichero);

			tEjecucion.put(i, valores.gettEjecucion());
			tSincro.put(i, valores.gettSincro());
			tTotal.put(i, valores.gettTotal());
			pUtil.put(i, valores.getpUtil());
		}
		graphsapp = new OverlaidPlot("Tiempo de ejecución", contentPane,tEjecucion);
		graphsapp.pack();
		graphsapp = new OverlaidPlot("Tiempo de sincronización", contentPane,tSincro);
		graphsapp.pack();
		graphsapp = new OverlaidPlot("Tiempo total", contentPane, tTotal);
		graphsapp.pack();
		graphsapp = new OverlaidPlot("Porcentaje de utilidad de CPU", contentPane, pUtil);
		graphsapp.pack();
		
		grafica.setVisible(true);
	}
	
	public Graficas() {
		super();
		setTitle("Gráficas");
		setBounds(250, 150, 1200, 800);
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		/** Content Pane */
		contentPane = new JPanel();
		contentPane.setBackground(colorprincipal);
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		contentPane.setLayout(new GridLayout(2, 2));
		setContentPane(contentPane);
	}

}
